# Generated by Django 5.0.2 on 2024-03-04 15:42

from django.db import migrations

def delete_all_rows(apps, schema_editor):
    
    City = apps.get_model('chatbot', 'City')
    City.objects.all().delete()
    Distance = apps.get_model('chatbot', 'Distance')
    Distance.objects.all().delete()
    FlightTime = apps.get_model('chatbot', 'FlightTime')
    FlightTime.objects.all().delete()
    TravelPackage = apps.get_model('chatbot', 'TravelPackage')
    TravelPackage.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(delete_all_rows),
    ]
