# Generated by Django 5.0.2 on 2024-03-04 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_auto_20240304_1542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distance",
            name="from_city",
        ),
        migrations.RemoveField(
            model_name="distance",
            name="to_city",
        ),
        migrations.RemoveField(
            model_name="travelpackage",
            name="destinations",
        ),
        migrations.DeleteModel(
            name="FlightTime",
        ),
        migrations.DeleteModel(
            name="Distance",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="TravelPackage",
        ),
    ]
