"""Initial migration

Revision ID: 8cc8bdbad57f
Revises: 
Create Date: 2024-03-19 09:55:48.389277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc8bdbad57f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Cityname', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_Cityname'), 'cities', ['Cityname'], unique=False)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('travel_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_agents_id'), 'travel_agents', ['id'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('Airportname', sa.String(length=255), nullable=True),
    sa.Column('iata_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('travel_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('packagename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('origin_city_id', sa.Integer(), nullable=True),
    sa.Column('destination_city_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['travel_agents.id'], ),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_packages_id'), 'travel_packages', ['id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=True),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=True),
    sa.Column('flight_duration', sa.Float(), nullable=True),
    sa.Column('operating_airlines', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_travel_packages_id'), table_name='travel_packages')
    op.drop_table('travel_packages')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_travel_agents_id'), table_name='travel_agents')
    op.drop_table('travel_agents')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_Cityname'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
